# Generated by Django 3.2.3 on 2022-03-30 14:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('major', models.CharField(choices=[('AT', 'BET-AT'), ('CT', 'BET-CT'), ('CoET', 'BET-CoET'), ('EsET', 'BET-EsET'), ('ET', 'BET-ET'), ('MT', 'BET-MT'), ('PPT', 'BET-PPT')], max_length=10, verbose_name='major')),
                ('idNumber', models.IntegerField(unique=True, verbose_name='studentId')),
                ('userType', models.CharField(choices=[('DIT', 'Department of Industrial Technology'), ('OAA', 'Office of Academic Affairs'), ('OCL', 'Office of Campus Librarian'), ('ORE', 'Office of Research and Extension'), ('Adviser', 'Thesis Adviser'), ('FIC', 'Subject Teacher')], max_length=10, verbose_name='userType')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='dateTime')),
                ('proponents', models.CharField(max_length=50, unique=True, verbose_name='proponents')),
                ('thesisTitle', models.TextField(verbose_name='title')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dit', models.BooleanField(default=False, verbose_name='DIT')),
                ('oaa', models.BooleanField(default=False, verbose_name='OAA')),
                ('ocl', models.BooleanField(default=False, verbose_name='OCL')),
                ('ore', models.BooleanField(default=False, verbose_name='ORE')),
                ('adviser', models.BooleanField(default=False, verbose_name='ADVISER')),
                ('fic', models.BooleanField(default=False, verbose_name='FIC')),
                ('proponents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acknowledgementReceipt.application')),
            ],
        ),
    ]
