# Generated by Django 3.2.3 on 2022-04-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='userType',
            field=models.CharField(choices=[('DIT', 'Department of Industrial Technology'), ('OAA', 'Office of Academic Affairs'), ('OCL', 'Office of Campus Librarian'), ('ORE', 'Office of Research and Extension'), ('Adviser', 'Thesis Adviser'), ('FIC', 'Subject Teacher'), ('ADMIN', 'Admin')], max_length=10, verbose_name='userType'),
        ),
    ]
